### ISSUE TITLE
更新clash链接

### ISSUE THREAD

**Issue by Junzhou-Chen** [onlypeng/clashtools#6]
是否可以更新clash下载链接，原clash地址无法访问目前

**Comment by onlypeng** [comment]
最新版本可以正常使用,你可以尝试修改一下github_proxy,自带的github代理好像有的dns被过滤了，无法正常访问

**Comment by onlypeng** [comment]
> 是否可以更新clash下载链接，原clash地址无法访问目前


最新版本可以正常使用,你可以尝试修改一下github_proxy,自带的github代理好像有被dns服务器的过滤了，无法正常访问。如果电脑可以访问github,把代理地址删除，让他直接链接github

**Comment by Junzhou-Chen** [comment]
嗯嗯，十分感谢，已成功配置，请问是否可以通过shell选择节点呢，远程服务器没有可视化

**Comment by onlypeng** [comment]
> 嗯嗯，十分感谢，已成功配置，请问是否可以通过shell选择节点呢，远程服务器没有可视化

你可以安装ui，它支持ui的
