### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by iockx** [onlypeng/clashtools#7]
```sh
[root@192 docker]# sh clashtool.sh install
检测是否缺少依赖
初始化配置文件
配置文件初始化成功                                                                     [  OK  ]
cp: '/usr/local/docker/clashtool.sh' and '/usr/local/docker/clashtool.sh' are the same file
获取版本失败                                                                           [FAILED]
```

centos 7版本..

**Comment by onlypeng** [comment]
> ```shell
> [root@192 docker]# sh clashtool.sh install
> 检测是否缺少依赖
> 初始化配置文件
> 配置文件初始化成功                                                                     [  OK  ]
> cp: '/usr/local/docker/clashtool.sh' and '/usr/local/docker/clashtool.sh' are the same file
> 获取版本失败                                                                           [FAILED]
> ```
> 
> centos 7版本..

复制文件报错我没看出来因为什么，复制文件和黏贴为一个地址，修改过脚本？？
获取版本失败是因为通过直连githu获取，暂时无法使用代理,有可能访问不了github，可以手动指定版本。例如 ./clashtool.sh install 2.0.24
