### ISSUE TITLE
大佬看一下 这是什么情况

### ISSUE THREAD

**Issue by lmxslpc** [onlypeng/clashtools#8]
正在检测订阅地址有效性...
订阅地址有效                                                                           [  OK  ]
开始下载1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12044    0 12044    0     0  14980      0 --:--:-- --:--:-- --:--:-- 14980
1下载成功                                                                              [  OK  ]
配置文件错误                                                                           [FAILED]
        time="2023-11-27T21:06:37+08:00" level=error msg="yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `dHJvamF...` into config.RawConfig"
configuration file /opt/clash/config/subscribe/1.new.yaml test failed

**Comment by onlypeng** [comment]
> 正在检测订阅地址有效性... 订阅地址有效 [ OK ] 开始下载1 % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 12044 0 12044 0 0 14980 0 --:--:-- --:--:-- --:--:-- 14980 1下载成功 [ OK ] 配置文件错误 [FAILED] time="2023-11-27T21:06:37+08:00" level=error msg="yaml: unmarshal errors: line 1: cannot unmarshal !!str `dHJvamF...` into config.RawConfig" configuration file /opt/clash/config/subscribe/1.new.yaml test failed

校验下载下来的配置文件是错误的，你查看一下  /opt/clash/config/subscribe/1.new.yaml 这个配置文件是否下载成功

**Comment by lmxslpc** [comment]
没有这个文件

**Comment by lmxslpc** [comment]
有这个文件 但是进去是乱码

**Comment by onlypeng** [comment]
> 没有这个文件

不应该啊，你使用代理下载没，你尝试访问配置文件url地址，看看能正常访问到配置文件不能

**Comment by lmxslpc** [comment]
直接浏览器访问也是乱码  用clashforwindows下载就正常配置文件

**Comment by lmxslpc** [comment]
https://sub3.smallstrawberry.com/api/v1/client/subscribe?token=xxxxxxxxxxxxxxxx   这种链接

**Comment by onlypeng** [comment]
你是不是购买后给的你配置文件，这个一般会进行加密，你解密后可以上传到服务器通过add命令添加本地配置文件添加进去，例如 ./clashtool.sh add 文件名::文件绝对路径

**Comment by onlypeng** [comment]
我这个暂时不支持直接下载解密配置文件，那样体量有点大

**Comment by lmxslpc** [comment]
恩 我直接导入好了
